"""Static configuration for the scanner."""

WATCHLIST = ["AAPL", "MSFT", "NVDA"]

DEFAULT_PERIOD = "6mo"
DEFAULT_STRATEGIES = ["mean-reversion", "rsi-reversal", "moving-average-trend"]

MEAN_REVERSION_WINDOW = 20
MEAN_REVERSION_ENTRY_Z = 2.0

RSI_WINDOW = 14
RSI_OVERSOLD = 30.0
RSI_OVERBOUGHT = 70.0

TREND_FAST_WINDOW = 20
TREND_SLOW_WINDOW = 50

ACCOUNT_EQUITY = 10_000.0
RISK_PER_TRADE = 0.01
